/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package threadsProject;

class SomeThread extends Thread {
    
    @Override
    public void run() {
        for (int i = 0; i <= 10; i++)
            System.out.println("Number - " + i);
    }
}

public class App {
    public static void main(String[] args) {
        SomeThread test = new SomeThread();
        test.start();
        
        SomeThread test1 = new SomeThread();
        test1.start();
        
        Thread t1 = new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i <= 10; i++)
                        System.out.println("Number - " + i);
                }
        });
        t1.start();
    }
}
